# Create docker compose with postgres and redis
version: "3.7"

services:
  postgres-chat:
    image: postgres:16.3-alpine3.20
    container_name: postgres-chat
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat-db
    ports:
      - "5430:5432"
    volumes:
      - postgres-chat-data:/var/lib/postgresql/data

  postgres-user:
    image: postgres:16.3-alpine3.20
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-db
    ports:
      - "5431:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-chat-data:
  postgres-user-data:
  redis-data:
  rabbitmq-data:
