# Create docker compose with postgres and redis
version: "3.7"

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    ports:
      - "6379:6379"
