apiVersion: v1
kind: ConfigMap
metadata:
  name: jibber-gateway-config
data:
  NODE_ENV: "production"
  APP_NAME: "JibberGateway"
  APP_VERSION: "1.0.0"
  APP_PORT: "3000"
  FRONT_DOMAIN: "http://localhost:3000"
  AUTH_DOMAIN: "auth.example.com"
  AUTH_JWT_KEY: "random_generated_jwt_key"
  USER_SERVICE_HOST: "localhost"
  USER_SERVICE_PORT: "4001"
  CHAT_SERVICE_HOST: "localhost"
  CHAT_SERVICE_PORT: "4002"
  MEDIA_SERVICE_HOST: "localhost"
  MEDIA_SERVICE_PORT: "4003"
